;    GRDB - debugger for dos with 32-bit extensions
;    Copyright (C) 1997-2006  David Lindauer
;
;    This program is free software; you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation; either version 2 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License
;    along with this program; if not, write to the Free Software
;    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
;
;    (for GNU General public license see file COPYING)
;
;    you may contact the author at:  mailto::camille@bluegrass.net
; 
;    or by snail mail at:
;
;    David Lindauer
;    850 Washburn Ave.  Apt #99
;    Louisville, KY 40222
;
	EXTRN	AOP0: proc
	EXTRN	AOP1: proc
	EXTRN	AOP2: proc
	EXTRN	AOP3: proc
	EXTRN	AOP4: proc
	EXTRN	AOP5: proc
	EXTRN	AOP6: proc
	EXTRN	AOP7: proc
	EXTRN	AOP8: proc
	EXTRN	AOP9: proc
	EXTRN	AOP10 :proc
	EXTRN	AOP11: proc
	EXTRN	AOP12: proc
	EXTRN	AOP13: proc
	EXTRN	AOP14: proc
	EXTRN	AOP15: proc
	EXTRN	AOP16: proc
	EXTRN	AOP17: proc
	EXTRN	AOP18: proc
	EXTRN	AOP19: proc
	EXTRN	AOP20 :proc
	EXTRN	AOP21: proc
	EXTRN	AOP22: proc
	EXTRN	AOP23: proc
	EXTRN	AOP24: proc
	EXTRN	AOP25: proc
	EXTRN	AOP26: proc
	EXTRN	AOP27: proc
	EXTRN	AOP28: proc
	EXTRN	AOP29: proc
	EXTRN	AOP30 :proc
	EXTRN	AOP31: proc
	EXTRN	AOP32: proc
	EXTRN	AOP33: proc
	EXTRN	AOP34: proc
	EXTRN	AOP35: proc
	EXTRN	AOP36: proc
	EXTRN	AOP37: proc
	EXTRN	AOP38: proc
	EXTRN	AOP39: proc
	EXTRN	AOP40 :proc
	EXTRN	AOP41: proc
	EXTRN	AOP42: proc
	EXTRN	AOP43: proc
	EXTRN	AOP44: proc
	EXTRN	AOP45: proc
	EXTRN	AOP46 :proc
	EXTRN	AOP47: proc
	EXTRN	AOP48 : PROC
	EXTRN	AOP48 : PROC
	EXTRN	AOP49: PROC
	EXTRN	AOP50: PROC
	EXTRN	AOP51 : PROC
	EXTRN	AOP52 : PROC
	EXTRN	AOP53:PROC
	EXTRN	AOP54:PROC
	EXTRN	AOP55:PROC
	EXTRN	AOP56:PROC
	EXTRN	AOP57 : PROC
	EXTRN	AOP58 : PROC
  EXTRN AOP59 : PROC
  EXTRN AOP60 : PROC
  EXTRN AOP61 : PROC
  EXTRN AOP62 : PROC
  EXTRN AOP63 : PROC
  EXTRN AOP64 : PROC
  EXTRN AOP65 : PROC
  EXTRN AOP66 : PROC
  EXTRN AOP67 : PROC
  EXTRN AOP68 : PROC
  EXTRN AOP69 : PROC
  EXTRN aop70 : PROC